{{- $affinity := merge dict .Values.common.affinity .Values.operator.affinity -}}
{{- $annotations := merge dict .Values.common.annotations .Values.operator.annotations -}}
{{- $dnsConfig := merge dict .Values.common.dnsConfig .Values.operator.dnsConfig -}}
{{- $env := concat .Values.common.env .Values.operator.env -}}
{{- $envFrom := concat .Values.common.envFrom .Values.operator.envFrom -}}
{{- $hostAliases := concat .Values.common.hostAliases .Values.operator.hostAliases -}}
{{- $imagePullSecrets := concat .Values.common.imagePullSecrets .Values.operator.imagePullSecrets -}}
{{- $initContainers := concat .Values.common.initContainers .Values.operator.initContainers -}}
{{- $podAnnotations := merge dict .Values.common.podAnnotations .Values.operator.podAnnotations -}}
{{- $revisionHistoryLimit := .Values.operator.revisionHistoryLimit | default .Values.common.revisionHistoryLimit -}}
{{- $runtimeClassName := .Values.operator.runtimeClassName | default .Values.common.runtimeClassName -}}
{{- $schedulerName := .Values.operator.schedulerName | default .Values.common.schedulerName -}}
{{- $tolerations := concat .Values.common.tolerations .Values.operator.tolerations -}}
{{- $topologySpreadConstraints := concat .Values.common.topologySpreadConstraints .Values.operator.topologySpreadConstraints -}}
{{- $volumeMounts := concat .Values.common.volumeMounts .Values.operator.volumeMounts -}}
{{- $volumes := concat .Values.common.volumes .Values.operator.volumes -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferriskey-operator.operator.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ferriskey-operator.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  {{- if ne $revisionHistoryLimit nil }}
  revisionHistoryLimit: {{ $revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ferriskey-operator.operator.podLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with $podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ferriskey-operator.operator.podLabels" . | nindent 8 }}
    spec:
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: operator
          {{- with .Values.operator.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Values.common.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.operator.image.pullPolicy | default .Values.common.image.pullPolicy }}
          {{- with .Values.operator.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.operator.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if ne .Values.operator.hostIPC nil }}
      hostIPC: {{ .Values.operator.hostIPC }}
      {{- end }}
      {{- if ne .Values.operator.hostNetwork nil }}
      hostNetwork: {{ .Values.operator.hostNetwork }}
      {{- end }}
      {{- if ne .Values.operator.hostPID nil }}
      hostPID: {{ .Values.operator.hostPID }}
      {{- end }}
      {{- if ne .Values.operator.hostUsers nil }}
      hostUsers: {{ .Values.operator.hostUsers }}
      {{- end }}
      {{- with $imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.nodeName }}
      nodeName: {{ .Values.operator.nodeName }}
      {{- end }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.operator.preemptionPolicy }}
      preemptionPolicy: {{ .Values.operator.preemptionPolicy }}
      {{- end }}
      {{- if ne .Values.operator.priority nil }}
      priority: {{ .Values.operator.priority }}
      {{- end }}
      {{- if .Values.operator.priorityClassName }}
      priorityClassName: {{ .Values.operator.priorityClassName }}
      {{- end }}
      {{- if $runtimeClassName }}
      runtimeClassName: {{ $runtimeClassName }}
      {{- end }}
      {{- if $schedulerName }}
      schedulerName: {{ $schedulerName }}
      {{- end }}
      {{- with .Values.operator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ferriskey-operator.operator.serviceAccountName" . }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
