/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`broker_callback`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BrokerCallbackError {
    Status400(models::ApiErrorResponse),
    Status401(models::ApiErrorResponse),
    Status502(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`broker_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BrokerLoginError {
    Status400(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// Processes the IdP callback, exchanges code for tokens, and redirects to client
pub async fn broker_callback(
    configuration: &configuration::Configuration,
    realm_name: &str,
    alias: &str,
    state: &str,
    code: Option<&str>,
    error: Option<&str>,
    error_description: Option<&str>,
) -> Result<(), Error<BrokerCallbackError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_alias = alias;
    let p_query_state = state;
    let p_query_code = code;
    let p_query_error = error;
    let p_query_error_description = error_description;

    let uri_str = format!(
        "{}/realms/{realm_name}/broker/{alias}/endpoint",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        alias = crate::apis::urlencode(p_path_alias)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_code {
        req_builder = req_builder.query(&[("code", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("state", &p_query_state.to_string())]);
    if let Some(ref param_value) = p_query_error {
        req_builder = req_builder.query(&[("error", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_error_description {
        req_builder = req_builder.query(&[("error_description", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<BrokerCallbackError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Redirects the user to the external identity provider for authentication
pub async fn broker_login(
    configuration: &configuration::Configuration,
    realm_name: &str,
    alias: &str,
    client_id: Option<&str>,
    redirect_uri: Option<&str>,
    response_type: Option<&str>,
    scope: Option<&str>,
    state: Option<&str>,
    nonce: Option<&str>,
    session_id: Option<&str>,
) -> Result<(), Error<BrokerLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_alias = alias;
    let p_query_client_id = client_id;
    let p_query_redirect_uri = redirect_uri;
    let p_query_response_type = response_type;
    let p_query_scope = scope;
    let p_query_state = state;
    let p_query_nonce = nonce;
    let p_query_session_id = session_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/broker/{alias}/login",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        alias = crate::apis::urlencode(p_path_alias)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_client_id {
        req_builder = req_builder.query(&[("client_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_redirect_uri {
        req_builder = req_builder.query(&[("redirect_uri", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_response_type {
        req_builder = req_builder.query(&[("response_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_scope {
        req_builder = req_builder.query(&[("scope", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_nonce {
        req_builder = req_builder.query(&[("nonce", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_session_id {
        req_builder = req_builder.query(&[("session_id", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<BrokerLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
