/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateClientError {
    Status400(models::ApiErrorResponse),
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_post_logout_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreatePostLogoutRedirectUriError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRedirectUriError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_role`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRoleError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteClientError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_post_logout_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeletePostLogoutRedirectUriError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRedirectUriError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client_roles`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientRolesError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_clients`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientsError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_post_logout_redirect_uris`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetPostLogoutRedirectUrisError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_redirect_uris`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRedirectUrisError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_client`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateClientError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_post_logout_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePostLogoutRedirectUriError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_redirect_uri`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateRedirectUriError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// Creates a new client within the specified realm. This endpoint allows you to register a new client application that can interact with the realm's resources.
pub async fn create_client(
    configuration: &configuration::Configuration,
    realm_name: &str,
    create_client_validator: models::CreateClientValidator,
) -> Result<models::Client, Error<CreateClientError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_body_create_client_validator = create_client_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_client_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Client`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Client`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateClientError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new post-logout redirect URI for the specified client.
pub async fn create_post_logout_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    create_redirect_uri_validator: models::CreateRedirectUriValidator,
) -> Result<models::RedirectUri, Error<CreatePostLogoutRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_body_create_redirect_uri_validator = create_redirect_uri_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/post-logout-redirects",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_redirect_uri_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RedirectUri`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RedirectUri`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreatePostLogoutRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new redirect URI for the specified client. This endpoint allows you to add a redirect URI that the client can use for OAuth2 or OpenID Connect flows.
pub async fn create_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    create_redirect_uri_validator: models::CreateRedirectUriValidator,
) -> Result<models::RedirectUri, Error<CreateRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_body_create_redirect_uri_validator = create_redirect_uri_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/redirects",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_redirect_uri_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RedirectUri`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RedirectUri`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new role for a specific client within a realm. This endpoint allows you to define roles that can be assigned to users or groups in the context of a client application.
pub async fn create_role(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    create_role_validator: models::CreateRoleValidator,
) -> Result<models::Role, Error<CreateRoleError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_body_create_role_validator = create_role_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/roles",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_role_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Role`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Role`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateRoleError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a client from the specified realm. This action is irreversible and will remove all associated data.
pub async fn delete_client(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<models::DeleteClientResponse, Error<DeleteClientError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteClientResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteClientResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteClientError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a specific post-logout redirect URI for a client in a realm.
pub async fn delete_post_logout_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    uri_id: &str,
) -> Result<(), Error<DeletePostLogoutRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_uri_id = uri_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/post-logout-redirects/{uri_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        uri_id = crate::apis::urlencode(p_path_uri_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeletePostLogoutRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a specific redirect URI for a client in a realm. This action is irreversible and will remove the redirect URI from the client's configuration.
pub async fn delete_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    uri_id: &str,
) -> Result<(), Error<DeleteRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_uri_id = uri_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/redirects/{uri_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        uri_id = crate::apis::urlencode(p_path_uri_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a client from the specified realm by its ID.
pub async fn get_client(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<models::GetClientResponse, Error<GetClientError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetClientResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetClientResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all roles associated with a client in a specific realm.
pub async fn get_client_roles(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<models::GetClientRolesResponse, Error<GetClientRolesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/roles",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetClientRolesResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::GetClientRolesResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientRolesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all clients associated with a specific realm.
pub async fn get_clients(
    configuration: &configuration::Configuration,
    realm_name: &str,
) -> Result<models::ClientsResponse, Error<GetClientsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all post-logout redirect URIs associated with a client in a specific realm.
pub async fn get_post_logout_redirect_uris(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<Vec<models::RedirectUri>, Error<GetPostLogoutRedirectUrisError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/post-logout-redirects",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::RedirectUri&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::RedirectUri&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetPostLogoutRedirectUrisError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all redirect URIs associated with a client in a specific realm. This endpoint is useful for OAuth2 or OpenID Connect flows where clients need to know their registered redirect URIs.
pub async fn get_redirect_uris(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<Vec<models::RedirectUri>, Error<GetRedirectUrisError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/redirects",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::RedirectUri&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::RedirectUri&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRedirectUrisError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing client in the specified realm. This endpoint allows you to modify client details such as name, client ID, and enabled status.
pub async fn update_client(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    update_client_validator: models::UpdateClientValidator,
) -> Result<models::UpdateClientResponse, Error<UpdateClientError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_body_update_client_validator = update_client_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_client_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateClientResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateClientResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateClientError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing post-logout redirect URI for a client in a specific realm.
pub async fn update_post_logout_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    uri_id: &str,
    update_redirect_uri_validator: models::UpdateRedirectUriValidator,
) -> Result<models::UpdatePostLogoutRedirectUriResponse, Error<UpdatePostLogoutRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_uri_id = uri_id;
    let p_body_update_redirect_uri_validator = update_redirect_uri_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/post-logout-redirects/{uri_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        uri_id = crate::apis::urlencode(p_path_uri_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_redirect_uri_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdatePostLogoutRedirectUriResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdatePostLogoutRedirectUriResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdatePostLogoutRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing redirect URI for a client in a specific realm. This endpoint allows you to modify the enabled status of a redirect URI.
pub async fn update_redirect_uri(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    uri_id: &str,
    update_redirect_uri_validator: models::UpdateRedirectUriValidator,
) -> Result<models::UpdateRedirectUriResponse, Error<UpdateRedirectUriError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_uri_id = uri_id;
    let p_body_update_redirect_uri_validator = update_redirect_uri_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/clients/{client_id}/redirects/{uri_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        uri_id = crate::apis::urlencode(p_path_uri_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_redirect_uri_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateRedirectUriResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateRedirectUriResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateRedirectUriError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
