/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`assign_default_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssignDefaultScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`assign_optional_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AssignOptionalScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_client_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateClientScopeError {
    Status400(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_protocol_mapper`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateProtocolMapperError {
    Status400(),
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_client_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteClientScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_protocol_mapper`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProtocolMapperError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client_client_scopes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientClientScopesError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_client_scopes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetClientScopesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unassign_default_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnassignDefaultScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`unassign_optional_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UnassignOptionalScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_client_scope`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateClientScopeError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_protocol_mapper`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateProtocolMapperError {
    UnknownValue(serde_json::Value),
}

/// Assigns a client scope as a default scope to the specified client. Default scopes are always included in tokens.
pub async fn assign_default_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    scope_id: &str,
) -> Result<models::ClientScopeMapping, Error<AssignDefaultScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_scope_id = scope_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/clients/{client_id}/default-client-scopes/{scope_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScopeMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScopeMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AssignDefaultScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Assigns a client scope as an optional scope to the specified client. Optional scopes are included only when explicitly requested.
pub async fn assign_optional_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    scope_id: &str,
) -> Result<models::ClientScopeMapping, Error<AssignOptionalScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_scope_id = scope_id;

    let uri_str = format!("{}/realms/{realm_name}/client-scopes/clients/{client_id}/optional-client-scopes/{scope_id}", configuration.base_path, realm_name=crate::apis::urlencode(p_path_realm_name), client_id=crate::apis::urlencode(p_path_client_id), scope_id=crate::apis::urlencode(p_path_scope_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScopeMapping`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScopeMapping`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AssignOptionalScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new client scope within the specified realm.
pub async fn create_client_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    create_client_scope_validator: models::CreateClientScopeValidator,
) -> Result<models::ClientScope, Error<CreateClientScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_body_create_client_scope_validator = create_client_scope_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_client_scope_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScope`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScope`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateClientScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new protocol mapper for the specified client scope.
pub async fn create_protocol_mapper(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
    create_protocol_mapper_validator: models::CreateProtocolMapperValidator,
) -> Result<models::ProtocolMapper, Error<CreateProtocolMapperError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;
    let p_body_create_protocol_mapper_validator = create_protocol_mapper_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}/protocol-mappers",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_protocol_mapper_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProtocolMapper`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProtocolMapper`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateProtocolMapperError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a client scope from the specified realm. This action is irreversible.
pub async fn delete_client_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
) -> Result<models::DeleteClientScopeResponse, Error<DeleteClientScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteClientScopeResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteClientScopeResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteClientScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes a protocol mapper from the specified client scope.
pub async fn delete_protocol_mapper(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
    mapper_id: &str,
) -> Result<models::DeleteProtocolMapperResponse, Error<DeleteProtocolMapperError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;
    let p_path_mapper_id = mapper_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}/protocol-mappers/{mapper_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id),
        mapper_id = crate::apis::urlencode(p_path_mapper_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteProtocolMapperResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteProtocolMapperResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteProtocolMapperError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns all client scopes (default and optional) assigned to the specified client.
pub async fn get_client_client_scopes(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
) -> Result<Vec<models::ClientScope>, Error<GetClientClientScopesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/clients/{client_id}/client-scopes",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ClientScope&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ClientScope&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientClientScopesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a client scope from the specified realm by its ID.
pub async fn get_client_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
) -> Result<models::ClientScope, Error<GetClientScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScope`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScope`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all client scopes associated with a specific realm.
pub async fn get_client_scopes(
    configuration: &configuration::Configuration,
    realm_name: &str,
) -> Result<models::ClientScopesResponse, Error<GetClientScopesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScopesResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScopesResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetClientScopesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Removes a client scope from the default scopes of the specified client.
pub async fn unassign_default_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    scope_id: &str,
) -> Result<(), Error<UnassignDefaultScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_scope_id = scope_id;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/clients/{client_id}/default-client-scopes/{scope_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        client_id = crate::apis::urlencode(p_path_client_id),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UnassignDefaultScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Removes a client scope from the optional scopes of the specified client.
pub async fn unassign_optional_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    client_id: &str,
    scope_id: &str,
) -> Result<(), Error<UnassignOptionalScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_client_id = client_id;
    let p_path_scope_id = scope_id;

    let uri_str = format!("{}/realms/{realm_name}/client-scopes/clients/{client_id}/optional-client-scopes/{scope_id}", configuration.base_path, realm_name=crate::apis::urlencode(p_path_realm_name), client_id=crate::apis::urlencode(p_path_client_id), scope_id=crate::apis::urlencode(p_path_scope_id));
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<UnassignOptionalScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing client scope in the specified realm.
pub async fn update_client_scope(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
    update_client_scope_validator: models::UpdateClientScopeValidator,
) -> Result<models::ClientScope, Error<UpdateClientScopeError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;
    let p_body_update_client_scope_validator = update_client_scope_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_client_scope_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClientScope`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClientScope`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateClientScopeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Updates an existing protocol mapper for the specified client scope.
pub async fn update_protocol_mapper(
    configuration: &configuration::Configuration,
    realm_name: &str,
    scope_id: &str,
    mapper_id: &str,
    update_protocol_mapper_validator: models::UpdateProtocolMapperValidator,
) -> Result<models::ProtocolMapper, Error<UpdateProtocolMapperError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_scope_id = scope_id;
    let p_path_mapper_id = mapper_id;
    let p_body_update_protocol_mapper_validator = update_protocol_mapper_validator;

    let uri_str = format!(
        "{}/realms/{realm_name}/client-scopes/{scope_id}/protocol-mappers/{mapper_id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        scope_id = crate::apis::urlencode(p_path_scope_id),
        mapper_id = crate::apis::urlencode(p_path_mapper_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_protocol_mapper_validator);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProtocolMapper`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProtocolMapper`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateProtocolMapperError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
