/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateProviderError {
    Status400(models::ApiErrorResponse),
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteProviderError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProviderError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_providers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListProvidersError {
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`sync_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SyncUsersError {
    Status401(),
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`test_connection`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TestConnectionError {
    Status401(),
    Status403(),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_provider`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateProviderError {
    Status400(models::ApiErrorResponse),
    Status401(models::ApiErrorResponse),
    Status403(models::ApiErrorResponse),
    Status404(models::ApiErrorResponse),
    Status500(models::ApiErrorResponse),
    UnknownValue(serde_json::Value),
}

pub async fn create_provider(
    configuration: &configuration::Configuration,
    realm_name: &str,
    create_provider_request: models::CreateProviderRequest,
) -> Result<models::ProviderResponse, Error<CreateProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_body_create_provider_request = create_provider_request;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_create_provider_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProviderResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProviderResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn delete_provider(
    configuration: &configuration::Configuration,
    realm_name: &str,
    id: &str,
) -> Result<models::DeleteProviderResponse, Error<DeleteProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_id = id;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers/{id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::DeleteProviderResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::DeleteProviderResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_provider(
    configuration: &configuration::Configuration,
    realm_name: &str,
    id: &str,
) -> Result<models::ProviderResponse, Error<GetProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_id = id;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers/{id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProviderResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProviderResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_providers(
    configuration: &configuration::Configuration,
    realm_name: &str,
) -> Result<models::ListProvidersResponse, Error<ListProvidersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ListProvidersResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ListProvidersResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListProvidersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Triggers synchronization of users from the external federation provider (LDAP, Kerberos, etc.) to the local IAM database. This performs a comprehensive diff and reconciliation.
pub async fn sync_users(
    configuration: &configuration::Configuration,
    realm_name: &str,
    id: &str,
) -> Result<models::SyncUsersResponse, Error<SyncUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_id = id;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers/{id}/sync-users",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::SyncUsersResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::SyncUsersResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SyncUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Tests the connection to the external federation provider (LDAP, Kerberos, etc.) to verify configuration and connectivity
pub async fn test_connection(
    configuration: &configuration::Configuration,
    realm_name: &str,
    id: &str,
) -> Result<models::TestConnectionResponse, Error<TestConnectionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_id = id;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers/{id}/test-connection",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::TestConnectionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::TestConnectionResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TestConnectionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_provider(
    configuration: &configuration::Configuration,
    realm_name: &str,
    id: &str,
    update_provider_request: models::UpdateProviderRequest,
) -> Result<models::UpdateProviderResponse, Error<UpdateProviderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_realm_name = realm_name;
    let p_path_id = id;
    let p_body_update_provider_request = update_provider_request;

    let uri_str = format!(
        "{}/realms/{realm_name}/federation/providers/{id}",
        configuration.base_path,
        realm_name = crate::apis::urlencode(p_path_realm_name),
        id = crate::apis::urlencode(p_path_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_update_provider_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::UpdateProviderResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::UpdateProviderResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateProviderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
