import {
  Columns3,
  Image,
  Layout,
  LetterText,
  Minus,
  MousePointerClick,
  MoveVertical,
  PanelTop,
  Share2,
  Table,
  Type,
  Navigation,
  Box,
} from 'lucide-react'
import type { ComponentDefinition, BuilderNode } from '../builder-core'

export const mjmlComponents: ComponentDefinition[] = [
  {
    type: 'mj-section',
    label: 'Section',
    icon: <Layout size={14} />,
    isContainer: true,
    allowedChildren: ['mj-column'],
    defaultProps: {},
    defaultStyles: {},
  },
  {
    type: 'mj-column',
    label: 'Column',
    icon: <Columns3 size={14} />,
    isContainer: true,
    allowedChildren: [
      'mj-text',
      'mj-image',
      'mj-button',
      'mj-divider',
      'mj-spacer',
      'mj-social',
      'mj-table',
      'mj-raw',
    ],
    defaultProps: {},
    defaultStyles: {},
  },
  {
    type: 'mj-text',
    label: 'Text',
    icon: <Type size={14} />,
    hasContent: true,
    defaultProps: { 'font-size': '14px', 'color': '#333333' },
    defaultStyles: {},
  },
  {
    type: 'mj-image',
    label: 'Image',
    icon: <Image size={14} />,
    defaultProps: {
      src: 'https://via.placeholder.com/600x200',
      alt: '',
      width: '600px',
    },
    defaultStyles: {},
  },
  {
    type: 'mj-button',
    label: 'Button',
    icon: <MousePointerClick size={14} />,
    hasContent: true,
    defaultProps: {
      'href': '#',
      'background-color': '#007bff',
      'color': '#ffffff',
      'font-size': '14px',
      'border-radius': '4px',
    },
    defaultStyles: {},
  },
  {
    type: 'mj-divider',
    label: 'Divider',
    icon: <Minus size={14} />,
    defaultProps: {
      'border-color': '#cccccc',
      'border-style': 'solid',
      'border-width': '1px',
    },
    defaultStyles: {},
  },
  {
    type: 'mj-spacer',
    label: 'Spacer',
    icon: <MoveVertical size={14} />,
    defaultProps: { height: '20px' },
    defaultStyles: {},
  },
  {
    type: 'mj-hero',
    label: 'Hero',
    icon: <PanelTop size={14} />,
    isContainer: true,
    allowedChildren: ['mj-text', 'mj-image', 'mj-button'],
    defaultProps: { mode: 'fluid-height' },
    defaultStyles: {},
  },
  {
    type: 'mj-wrapper',
    label: 'Wrapper',
    icon: <Box size={14} />,
    isContainer: true,
    allowedChildren: ['mj-section'],
    defaultProps: {},
    defaultStyles: {},
  },
  {
    type: 'mj-social',
    label: 'Social',
    icon: <Share2 size={14} />,
    defaultProps: { mode: 'horizontal', 'icon-size': '20px' },
    defaultStyles: {},
  },
  {
    type: 'mj-navbar',
    label: 'Navbar',
    icon: <Navigation size={14} />,
    defaultProps: {},
    defaultStyles: {},
  },
  {
    type: 'mj-table',
    label: 'Table',
    icon: <Table size={14} />,
    hasContent: true,
    defaultProps: { width: '100%' },
    defaultStyles: {},
  },
  {
    type: 'mj-raw',
    label: 'Raw HTML',
    icon: <LetterText size={14} />,
    hasContent: true,
    defaultProps: {},
    defaultStyles: {},
  },
]

export function getDefaultNode(type: string): Omit<BuilderNode, 'id'> {
  const def = mjmlComponents.find((c) => c.type === type)
  return {
    type,
    props: { ...(def?.defaultProps ?? {}) },
    styles: { ...(def?.defaultStyles ?? {}) },
    children: [],
    content: def?.hasContent ? (type === 'mj-text' ? '<p>Text</p>' : type === 'mj-button' ? 'Click me' : '') : undefined,
  }
}
