//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "client_scopes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub protocol: String,
    pub is_default: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_scope_attributes::Entity")]
    ClientScopeAttributes,
    #[sea_orm(has_many = "super::client_scope_mappings::Entity")]
    ClientScopeMappings,
    #[sea_orm(has_many = "super::client_scope_protocol_mappers::Entity")]
    ClientScopeProtocolMappers,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
}

impl Related<super::client_scope_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeAttributes.def()
    }
}

impl Related<super::client_scope_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeMappings.def()
    }
}

impl Related<super::client_scope_protocol_mappers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeProtocolMappers.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        super::client_scope_mappings::Relation::Clients.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::client_scope_mappings::Relation::ClientScopes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
