//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "client_scopes"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub protocol: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub default_scope_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    Name,
    Description,
    Protocol,
    CreatedAt,
    UpdatedAt,
    DefaultScopeType,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ClientScopeAttributes,
    ClientScopeMappings,
    ClientScopeProtocolMappers,
    Realms,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Description => ColumnType::Text.def().null(),
            Self::Protocol => ColumnType::String(StringLen::N(255u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DefaultScopeType => ColumnType::String(StringLen::N(255u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ClientScopeAttributes => {
                Entity::has_many(super::client_scope_attributes::Entity).into()
            }
            Self::ClientScopeMappings => {
                Entity::has_many(super::client_scope_mappings::Entity).into()
            }
            Self::ClientScopeProtocolMappers => {
                Entity::has_many(super::client_scope_protocol_mappers::Entity).into()
            }
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
        }
    }
}

impl Related<super::client_scope_attributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeAttributes.def()
    }
}

impl Related<super::client_scope_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeMappings.def()
    }
}

impl Related<super::client_scope_protocol_mappers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeProtocolMappers.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        super::client_scope_mappings::Relation::Clients.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::client_scope_mappings::Relation::ClientScopes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
