//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "clients"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    pub client_id: String,
    pub secret: Option<String>,
    pub enabled: bool,
    pub protocol: String,
    pub public_client: bool,
    pub service_account_enabled: bool,
    pub client_type: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub direct_access_grants_enabled: Option<bool>,
    pub access_token_lifetime_secs: Option<i32>,
    pub refresh_token_lifetime_secs: Option<i32>,
    pub id_token_lifetime_secs: Option<i32>,
    pub temporary_token_lifetime_secs: Option<i32>,
    pub maintenance_enabled: Option<bool>,
    pub maintenance_reason: Option<String>,
    pub maintenance_session_strategy: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    Name,
    ClientId,
    Secret,
    Enabled,
    Protocol,
    PublicClient,
    ServiceAccountEnabled,
    ClientType,
    CreatedAt,
    UpdatedAt,
    DirectAccessGrantsEnabled,
    AccessTokenLifetimeSecs,
    RefreshTokenLifetimeSecs,
    IdTokenLifetimeSecs,
    TemporaryTokenLifetimeSecs,
    MaintenanceEnabled,
    MaintenanceReason,
    MaintenanceSessionStrategy,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AuthSessions,
    BrokerAuthSessions,
    ClientMaintenanceWhitelist,
    ClientScopeMappings,
    PostLogoutRedirectUris,
    Realms,
    RedirectUris,
    Roles,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::ClientId => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Secret => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::Enabled => ColumnType::Boolean.def(),
            Self::Protocol => ColumnType::String(StringLen::N(255u32)).def(),
            Self::PublicClient => ColumnType::Boolean.def(),
            Self::ServiceAccountEnabled => ColumnType::Boolean.def(),
            Self::ClientType => ColumnType::String(StringLen::N(255u32)).def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::DirectAccessGrantsEnabled => ColumnType::Boolean.def().null(),
            Self::AccessTokenLifetimeSecs => ColumnType::Integer.def().null(),
            Self::RefreshTokenLifetimeSecs => ColumnType::Integer.def().null(),
            Self::IdTokenLifetimeSecs => ColumnType::Integer.def().null(),
            Self::TemporaryTokenLifetimeSecs => ColumnType::Integer.def().null(),
            Self::MaintenanceEnabled => ColumnType::Boolean.def().null(),
            Self::MaintenanceReason => ColumnType::Text.def().null(),
            Self::MaintenanceSessionStrategy => {
                ColumnType::String(StringLen::N(50u32)).def().null()
            }
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AuthSessions => Entity::has_many(super::auth_sessions::Entity).into(),
            Self::BrokerAuthSessions => {
                Entity::has_many(super::broker_auth_sessions::Entity).into()
            }
            Self::ClientMaintenanceWhitelist => {
                Entity::has_many(super::client_maintenance_whitelist::Entity).into()
            }
            Self::ClientScopeMappings => {
                Entity::has_many(super::client_scope_mappings::Entity).into()
            }
            Self::PostLogoutRedirectUris => {
                Entity::has_many(super::post_logout_redirect_uris::Entity).into()
            }
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::RedirectUris => Entity::has_many(super::redirect_uris::Entity).into(),
            Self::Roles => Entity::has_many(super::roles::Entity).into(),
            Self::Users => Entity::has_one(super::users::Entity).into(),
        }
    }
}

impl Related<super::auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthSessions.def()
    }
}

impl Related<super::broker_auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BrokerAuthSessions.def()
    }
}

impl Related<super::client_maintenance_whitelist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientMaintenanceWhitelist.def()
    }
}

impl Related<super::client_scope_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopeMappings.def()
    }
}

impl Related<super::post_logout_redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostLogoutRedirectUris.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::redirect_uris::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RedirectUris.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::client_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        super::client_scope_mappings::Relation::ClientScopes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::client_scope_mappings::Relation::Clients.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
