//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "client_scope_mappings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub client_scope_id: Uuid,
    pub is_default: bool,
    pub is_optional: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client_scopes::Entity",
        from = "Column::ClientScopeId",
        to = "super::client_scopes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ClientScopes,
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Clients,
}

impl Related<super::client_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopes.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
