//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "client_scope_protocol_mappers"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub client_scope_id: Uuid,
    pub name: String,
    pub mapper_type: String,
    pub config: Json,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ClientScopeId,
    Name,
    MapperType,
    Config,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ClientScopes,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::ClientScopeId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::MapperType => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Config => ColumnType::JsonBinary.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ClientScopes => Entity::belongs_to(super::client_scopes::Entity)
                .from(Column::ClientScopeId)
                .to(super::client_scopes::Column::Id)
                .into(),
        }
    }
}

impl Related<super::client_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
