//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "client_scope_mappings"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub client_id: Uuid,
    pub client_scope_id: Uuid,
    pub default_scope_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ClientId,
    ClientScopeId,
    DefaultScopeType,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ClientId,
    ClientScopeId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Uuid, Uuid);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ClientScopes,
    Clients,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ClientId => ColumnType::Uuid.def(),
            Self::ClientScopeId => ColumnType::Uuid.def(),
            Self::DefaultScopeType => ColumnType::String(StringLen::N(255u32)).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ClientScopes => Entity::belongs_to(super::client_scopes::Entity)
                .from(Column::ClientScopeId)
                .to(super::client_scopes::Column::Id)
                .into(),
            Self::Clients => Entity::belongs_to(super::clients::Entity)
                .from(Column::ClientId)
                .to(super::clients::Column::Id)
                .into(),
        }
    }
}

impl Related<super::client_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientScopes.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
