//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compass_flow_steps")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub flow_id: Uuid,
    pub step_name: String,
    pub status: String,
    pub duration_ms: Option<i64>,
    pub error_code: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub started_at: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::compass_flows::Entity",
        from = "Column::FlowId",
        to = "super::compass_flows::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CompassFlows,
}

impl Related<super::compass_flows::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompassFlows.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
