//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod access_tokens;
pub mod auth_sessions;
pub mod broker_auth_sessions;
pub mod client_scope_attributes;
pub mod client_scope_mappings;
pub mod client_scope_protocol_mappers;
pub mod client_scopes;
pub mod clients;
pub mod credentials;
pub mod identity_provider_links;
pub mod identity_providers;
pub mod jwt_keys;
pub mod realm_settings;
pub mod realms;
pub mod redirect_uris;
pub mod refresh_tokens;
pub mod roles;
pub mod security_events;
pub mod user_federation_mappings;
pub mod user_federation_providers;
pub mod user_required_actions;
pub mod user_role;
pub mod user_sessions;
pub mod users;
pub mod webhook_subscribers;
pub mod webhooks;
