//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "portal_themes"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub design_tokens: Json,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub name: String,
    pub layout_id: Option<Uuid>,
    pub page_login: Json,
    pub page_register: Json,
    pub page_totp: Json,
    pub page_forgot_password: Json,
    pub page_reset_password: Json,
    pub page_magic_link_verify: Json,
    pub page_verify_email: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    DesignTokens,
    CreatedAt,
    UpdatedAt,
    Name,
    LayoutId,
    PageLogin,
    PageRegister,
    PageTotp,
    PageForgotPassword,
    PageResetPassword,
    PageMagicLinkVerify,
    PageVerifyEmail,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    PortalLayouts,
    RealmSettings,
    Realms,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::DesignTokens => ColumnType::JsonBinary.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::LayoutId => ColumnType::Uuid.def().null(),
            Self::PageLogin => ColumnType::JsonBinary.def(),
            Self::PageRegister => ColumnType::JsonBinary.def(),
            Self::PageTotp => ColumnType::JsonBinary.def(),
            Self::PageForgotPassword => ColumnType::JsonBinary.def(),
            Self::PageResetPassword => ColumnType::JsonBinary.def(),
            Self::PageMagicLinkVerify => ColumnType::JsonBinary.def(),
            Self::PageVerifyEmail => ColumnType::JsonBinary.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::PortalLayouts => Entity::belongs_to(super::portal_layouts::Entity)
                .from(Column::LayoutId)
                .to(super::portal_layouts::Column::Id)
                .into(),
            Self::RealmSettings => Entity::has_many(super::realm_settings::Entity).into(),
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
        }
    }
}

impl Related<super::portal_layouts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PortalLayouts.def()
    }
}

impl Related<super::realm_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmSettings.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
