//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "realm_settings"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub default_signing_algorithm: Option<String>,
    pub updated_at: DateTime,
    pub user_registration_enabled: bool,
    pub forgot_password_enabled: bool,
    pub remember_me_enabled: bool,
    pub magic_link_enabled: bool,
    pub magic_link_ttl_minutes: i32,
    pub compass_enabled: bool,
    pub access_token_lifetime_secs: i32,
    pub refresh_token_lifetime_secs: i32,
    pub id_token_lifetime_secs: i32,
    pub temporary_token_lifetime_secs: i32,
    pub passkey_enabled: bool,
    pub reset_password_template_id: Option<Uuid>,
    pub magic_link_template_id: Option<Uuid>,
    pub email_verification_template_id: Option<Uuid>,
    pub email_verification_enabled: bool,
    pub email_verification_ttl_hours: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    DefaultSigningAlgorithm,
    UpdatedAt,
    UserRegistrationEnabled,
    ForgotPasswordEnabled,
    RememberMeEnabled,
    MagicLinkEnabled,
    MagicLinkTtlMinutes,
    CompassEnabled,
    AccessTokenLifetimeSecs,
    RefreshTokenLifetimeSecs,
    IdTokenLifetimeSecs,
    TemporaryTokenLifetimeSecs,
    PasskeyEnabled,
    ResetPasswordTemplateId,
    MagicLinkTemplateId,
    EmailVerificationTemplateId,
    EmailVerificationEnabled,
    EmailVerificationTtlHours,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    EmailTemplates3,
    EmailTemplates2,
    EmailTemplates1,
    Realms,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::DefaultSigningAlgorithm => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
            Self::UserRegistrationEnabled => ColumnType::Boolean.def(),
            Self::ForgotPasswordEnabled => ColumnType::Boolean.def(),
            Self::RememberMeEnabled => ColumnType::Boolean.def(),
            Self::MagicLinkEnabled => ColumnType::Boolean.def(),
            Self::MagicLinkTtlMinutes => ColumnType::Integer.def(),
            Self::CompassEnabled => ColumnType::Boolean.def(),
            Self::AccessTokenLifetimeSecs => ColumnType::Integer.def(),
            Self::RefreshTokenLifetimeSecs => ColumnType::Integer.def(),
            Self::IdTokenLifetimeSecs => ColumnType::Integer.def(),
            Self::TemporaryTokenLifetimeSecs => ColumnType::Integer.def(),
            Self::PasskeyEnabled => ColumnType::Boolean.def(),
            Self::ResetPasswordTemplateId => ColumnType::Uuid.def().null(),
            Self::MagicLinkTemplateId => ColumnType::Uuid.def().null(),
            Self::EmailVerificationTemplateId => ColumnType::Uuid.def().null(),
            Self::EmailVerificationEnabled => ColumnType::Boolean.def(),
            Self::EmailVerificationTtlHours => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::EmailTemplates3 => Entity::belongs_to(super::email_templates::Entity)
                .from(Column::EmailVerificationTemplateId)
                .to(super::email_templates::Column::Id)
                .into(),
            Self::EmailTemplates2 => Entity::belongs_to(super::email_templates::Entity)
                .from(Column::MagicLinkTemplateId)
                .to(super::email_templates::Column::Id)
                .into(),
            Self::EmailTemplates1 => Entity::belongs_to(super::email_templates::Entity)
                .from(Column::ResetPasswordTemplateId)
                .to(super::email_templates::Column::Id)
                .into(),
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
        }
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
