//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "security_events"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub actor_id: Option<Uuid>,
    pub actor_type: Option<String>,
    pub event_type: String,
    pub status: String,
    pub target_type: Option<String>,
    pub target_id: Option<Uuid>,
    pub resource: Option<String>,
    pub timestamp: DateTime,
    pub trace_id: Option<String>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub details: Option<Json>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    ActorId,
    ActorType,
    EventType,
    Status,
    TargetType,
    TargetId,
    Resource,
    Timestamp,
    TraceId,
    IpAddress,
    UserAgent,
    Details,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Realms,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::ActorId => ColumnType::Uuid.def().null(),
            Self::ActorType => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::EventType => ColumnType::String(StringLen::N(50u32)).def(),
            Self::Status => ColumnType::String(StringLen::N(20u32)).def(),
            Self::TargetType => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::TargetId => ColumnType::Uuid.def().null(),
            Self::Resource => ColumnType::Text.def().null(),
            Self::Timestamp => ColumnType::DateTime.def(),
            Self::TraceId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::IpAddress => ColumnType::String(StringLen::N(45u32)).def().null(),
            Self::UserAgent => ColumnType::Text.def().null(),
            Self::Details => ColumnType::JsonBinary.def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
        }
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
