//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "user_federation_mappings"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub provider_id: Uuid,
    pub user_id: Uuid,
    pub external_id: String,
    pub external_username: String,
    pub mapping_metadata: Option<Json>,
    pub last_synced_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ProviderId,
    UserId,
    ExternalId,
    ExternalUsername,
    MappingMetadata,
    LastSyncedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    UserFederationProviders,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::ProviderId => ColumnType::Uuid.def(),
            Self::UserId => ColumnType::Uuid.def(),
            Self::ExternalId => ColumnType::String(StringLen::N(512u32)).def(),
            Self::ExternalUsername => ColumnType::String(StringLen::N(255u32)).def(),
            Self::MappingMetadata => ColumnType::JsonBinary.def().null(),
            Self::LastSyncedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::UserFederationProviders => {
                Entity::belongs_to(super::user_federation_providers::Entity)
                    .from(Column::ProviderId)
                    .to(super::user_federation_providers::Column::Id)
                    .into()
            }
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::user_federation_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProviders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
