//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user_federation_mappings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub provider_id: Uuid,
    pub user_id: Uuid,
    pub external_id: String,
    pub external_username: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub mapping_metadata: Option<Json>,
    pub last_synced_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_federation_providers::Entity",
        from = "Column::ProviderId",
        to = "super::user_federation_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    UserFederationProviders,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::user_federation_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProviders.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
