//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "user_federation_providers"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    pub provider_type: String,
    pub enabled: bool,
    pub priority: i32,
    pub config: Json,
    pub sync_enabled: bool,
    pub sync_mode: String,
    pub sync_interval_minutes: Option<i32>,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub last_sync_status: Option<String>,
    pub last_sync_result: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    Name,
    ProviderType,
    Enabled,
    Priority,
    Config,
    SyncEnabled,
    SyncMode,
    SyncIntervalMinutes,
    LastSyncAt,
    LastSyncStatus,
    LastSyncResult,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Realms,
    UserFederationMappings,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def(),
            Self::ProviderType => ColumnType::String(StringLen::N(50u32)).def(),
            Self::Enabled => ColumnType::Boolean.def(),
            Self::Priority => ColumnType::Integer.def(),
            Self::Config => ColumnType::JsonBinary.def(),
            Self::SyncEnabled => ColumnType::Boolean.def(),
            Self::SyncMode => ColumnType::String(StringLen::N(20u32)).def(),
            Self::SyncIntervalMinutes => ColumnType::Integer.def().null(),
            Self::LastSyncAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::LastSyncStatus => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::LastSyncResult => ColumnType::JsonBinary.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::UserFederationMappings => {
                Entity::has_many(super::user_federation_mappings::Entity).into()
            }
        }
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::user_federation_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMappings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
