//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "broker_auth_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub identity_provider_id: Uuid,
    pub client_id: Uuid,
    pub redirect_uri: String,
    pub response_type: String,
    pub scope: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub state: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub nonce: Option<String>,
    #[sea_orm(unique)]
    pub broker_state: String,
    pub code_verifier: Option<String>,
    pub auth_session_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub expires_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auth_sessions::Entity",
        from = "Column::AuthSessionId",
        to = "super::auth_sessions::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    AuthSessions,
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Clients,
    #[sea_orm(
        belongs_to = "super::identity_providers::Entity",
        from = "Column::IdentityProviderId",
        to = "super::identity_providers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IdentityProviders,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
}

impl Related<super::auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthSessions.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::identity_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IdentityProviders.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
