//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_federation_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub name: String,
    pub provider_type: String,
    pub enabled: bool,
    pub priority: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    pub sync_enabled: bool,
    pub sync_mode: String,
    pub sync_interval_minutes: Option<i32>,
    pub last_sync_at: Option<DateTimeWithTimeZone>,
    pub last_sync_status: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub last_sync_result: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
    #[sea_orm(has_many = "super::user_federation_mappings::Entity")]
    UserFederationMappings,
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::user_federation_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMappings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
