/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf4 {
    #[serde(rename = "Forbidden")]
    pub forbidden: String,
}

impl ApiErrorOneOf4 {
    pub fn new(forbidden: String) -> ApiErrorOneOf4 {
        ApiErrorOneOf4 { forbidden }
    }
}
