/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf2 {
    #[serde(rename = "NotFound")]
    pub not_found: String,
}

impl ApiErrorOneOf2 {
    pub fn new(not_found: String) -> ApiErrorOneOf2 {
        ApiErrorOneOf2 { not_found }
    }
}
