/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf1 {
    #[serde(rename = "UnProcessableEntity")]
    pub un_processable_entity: Vec<models::ValidationError>,
}

impl ApiErrorOneOf1 {
    pub fn new(un_processable_entity: Vec<models::ValidationError>) -> ApiErrorOneOf1 {
        ApiErrorOneOf1 {
            un_processable_entity,
        }
    }
}
