/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiErrorOneOf6 {
    #[serde(rename = "ServiceUnavailable")]
    pub service_unavailable: String,
}

impl ApiErrorOneOf6 {
    pub fn new(service_unavailable: String) -> ApiErrorOneOf6 {
        ApiErrorOneOf6 {
            service_unavailable,
        }
    }
}
