/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiError {
    ApiErrorOneOf(Box<models::ApiErrorOneOf>),
    ApiErrorOneOf1(Box<models::ApiErrorOneOf1>),
    ApiErrorOneOf2(Box<models::ApiErrorOneOf2>),
    ApiErrorOneOf3(Box<models::ApiErrorOneOf3>),
    ApiErrorOneOf4(Box<models::ApiErrorOneOf4>),
    ApiErrorOneOf5(Box<models::ApiErrorOneOf5>),
    ApiErrorOneOf6(Box<models::ApiErrorOneOf6>),
}

impl Default for ApiError {
    fn default() -> Self {
        Self::ApiErrorOneOf(Default::default())
    }
}
