/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationStatus {
    #[serde(rename = "Success")]
    Success,
    #[serde(rename = "RequiresActions")]
    RequiresActions,
    #[serde(rename = "RequiresOtpChallenge")]
    RequiresOtpChallenge,
    #[serde(rename = "Failed")]
    Failed,
}

impl std::fmt::Display for AuthenticationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "Success"),
            Self::RequiresActions => write!(f, "RequiresActions"),
            Self::RequiresOtpChallenge => write!(f, "RequiresOtpChallenge"),
            Self::Failed => write!(f, "Failed"),
        }
    }
}

impl Default for AuthenticationStatus {
    fn default() -> AuthenticationStatus {
        Self::Success
    }
}
