/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationAttemptResponse {
    #[serde(rename = "login_url")]
    pub login_url: String,
}

impl AuthenticationAttemptResponse {
    pub fn new(login_url: String) -> AuthenticationAttemptResponse {
        AuthenticationAttemptResponse { login_url }
    }
}
