/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkDeleteUserResponse {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "realm_name")]
    pub realm_name: String,
}

impl BulkDeleteUserResponse {
    pub fn new(count: i32, realm_name: String) -> BulkDeleteUserResponse {
        BulkDeleteUserResponse { count, realm_name }
    }
}
