/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BurnRecoveryCodeRequest {
    #[serde(rename = "recovery_code")]
    pub recovery_code: String,
    #[serde(rename = "recovery_code_format")]
    pub recovery_code_format: String,
}

impl BurnRecoveryCodeRequest {
    pub fn new(recovery_code: String, recovery_code_format: String) -> BurnRecoveryCodeRequest {
        BurnRecoveryCodeRequest {
            recovery_code,
            recovery_code_format,
        }
    }
}
