/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientScope {
    #[serde(
        rename = "attributes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attributes: Option<Option<Vec<models::ClientScopeAttribute>>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_default")]
    pub is_default: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(
        rename = "protocol_mappers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub protocol_mappers: Option<Option<Vec<models::ProtocolMapper>>>,
    #[serde(rename = "realm_id")]
    pub realm_id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ClientScope {
    pub fn new(
        created_at: String,
        id: uuid::Uuid,
        is_default: bool,
        name: String,
        protocol: String,
        realm_id: uuid::Uuid,
        updated_at: String,
    ) -> ClientScope {
        ClientScope {
            attributes: None,
            created_at,
            description: None,
            id,
            is_default,
            name,
            protocol,
            protocol_mappers: None,
            realm_id,
            updated_at,
        }
    }
}
