/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientScopeAttribute {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scope_id")]
    pub scope_id: uuid::Uuid,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<String>>,
}

impl ClientScopeAttribute {
    pub fn new(id: uuid::Uuid, name: String, scope_id: uuid::Uuid) -> ClientScopeAttribute {
        ClientScopeAttribute {
            id,
            name,
            scope_id,
            value: None,
        }
    }
}
