/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Client {
    #[serde(rename = "client_id")]
    pub client_id: String,
    #[serde(rename = "client_type")]
    pub client_type: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "direct_access_grants_enabled")]
    pub direct_access_grants_enabled: bool,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "public_client")]
    pub public_client: bool,
    #[serde(rename = "realm_id")]
    pub realm_id: uuid::Uuid,
    #[serde(
        rename = "redirect_uris",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redirect_uris: Option<Option<Vec<models::RedirectUri>>>,
    #[serde(
        rename = "secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secret: Option<Option<String>>,
    #[serde(rename = "service_account_enabled")]
    pub service_account_enabled: bool,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Client {
    pub fn new(
        client_id: String,
        client_type: String,
        created_at: String,
        direct_access_grants_enabled: bool,
        enabled: bool,
        id: uuid::Uuid,
        name: String,
        protocol: String,
        public_client: bool,
        realm_id: uuid::Uuid,
        service_account_enabled: bool,
        updated_at: String,
    ) -> Client {
        Client {
            client_id,
            client_type,
            created_at,
            direct_access_grants_enabled,
            enabled,
            id,
            name,
            protocol,
            public_client,
            realm_id,
            redirect_uris: None,
            secret: None,
            service_account_enabled,
            updated_at,
        }
    }
}
