/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientScopeMapping {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    #[serde(rename = "is_default")]
    pub is_default: bool,
    #[serde(rename = "is_optional")]
    pub is_optional: bool,
    #[serde(rename = "scope_id")]
    pub scope_id: uuid::Uuid,
}

impl ClientScopeMapping {
    pub fn new(
        client_id: uuid::Uuid,
        is_default: bool,
        is_optional: bool,
        scope_id: uuid::Uuid,
    ) -> ClientScopeMapping {
        ClientScopeMapping {
            client_id,
            is_default,
            is_optional,
            scope_id,
        }
    }
}
