/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProviderRequest {
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "provider_type")]
    pub provider_type: String,
    #[serde(rename = "sync_enabled")]
    pub sync_enabled: bool,
    #[serde(
        rename = "sync_interval_minutes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sync_interval_minutes: Option<Option<i32>>,
    #[serde(rename = "sync_mode")]
    pub sync_mode: String,
}

impl CreateProviderRequest {
    pub fn new(
        config: Option<serde_json::Value>,
        enabled: bool,
        name: String,
        priority: i32,
        provider_type: String,
        sync_enabled: bool,
        sync_mode: String,
    ) -> CreateProviderRequest {
        CreateProviderRequest {
            config,
            enabled,
            name,
            priority,
            provider_type,
            sync_enabled,
            sync_interval_minutes: None,
            sync_mode,
        }
    }
}
