/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateClientValidator {
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "client_type", skip_serializing_if = "Option::is_none")]
    pub client_type: Option<String>,
    #[serde(
        rename = "direct_access_grants_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub direct_access_grants_enabled: Option<bool>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(rename = "public_client", skip_serializing_if = "Option::is_none")]
    pub public_client: Option<bool>,
    #[serde(
        rename = "service_account_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_account_enabled: Option<bool>,
}

impl CreateClientValidator {
    pub fn new() -> CreateClientValidator {
        CreateClientValidator {
            client_id: None,
            client_type: None,
            direct_access_grants_enabled: None,
            enabled: None,
            name: None,
            protocol: None,
            public_client: None,
            service_account_enabled: None,
        }
    }
}
