/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProtocolMapperValidator {
    #[serde(
        rename = "config",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config: Option<Option<serde_json::Value>>,
    #[serde(rename = "mapper_type", skip_serializing_if = "Option::is_none")]
    pub mapper_type: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CreateProtocolMapperValidator {
    pub fn new() -> CreateProtocolMapperValidator {
        CreateProtocolMapperValidator {
            config: None,
            mapper_type: None,
            name: None,
        }
    }
}
