/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateIdentityProviderValidator {
    #[serde(
        rename = "add_read_token_role_on_create",
        skip_serializing_if = "Option::is_none"
    )]
    pub add_read_token_role_on_create: Option<bool>,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(
        rename = "config",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config: Option<Option<serde_json::Value>>,
    #[serde(
        rename = "display_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(
        rename = "first_broker_login_flow_alias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_broker_login_flow_alias: Option<Option<String>>,
    #[serde(rename = "link_only", skip_serializing_if = "Option::is_none")]
    pub link_only: Option<bool>,
    #[serde(
        rename = "post_broker_login_flow_alias",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub post_broker_login_flow_alias: Option<Option<String>>,
    #[serde(rename = "provider_id", skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    #[serde(rename = "store_token", skip_serializing_if = "Option::is_none")]
    pub store_token: Option<bool>,
    #[serde(rename = "trust_email", skip_serializing_if = "Option::is_none")]
    pub trust_email: Option<bool>,
}

impl CreateIdentityProviderValidator {
    pub fn new() -> CreateIdentityProviderValidator {
        CreateIdentityProviderValidator {
            add_read_token_role_on_create: None,
            alias: None,
            config: None,
            display_name: None,
            enabled: None,
            first_broker_login_flow_alias: None,
            link_only: None,
            post_broker_login_flow_alias: None,
            provider_id: None,
            store_token: None,
            trust_email: None,
        }
    }
}
