/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialDataOverviewOneOf1Federated {
    #[serde(rename = "provider_id")]
    pub provider_id: String,
    #[serde(rename = "provider_type")]
    pub provider_type: String,
}

impl CredentialDataOverviewOneOf1Federated {
    pub fn new(
        provider_id: String,
        provider_type: String,
    ) -> CredentialDataOverviewOneOf1Federated {
        CredentialDataOverviewOneOf1Federated {
            provider_id,
            provider_type,
        }
    }
}
