/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialDataOverviewOneOf1 {
    #[serde(rename = "Federated")]
    pub federated: Box<models::CredentialDataOverviewOneOf1Federated>,
}

impl CredentialDataOverviewOneOf1 {
    pub fn new(
        federated: models::CredentialDataOverviewOneOf1Federated,
    ) -> CredentialDataOverviewOneOf1 {
        CredentialDataOverviewOneOf1 {
            federated: Box::new(federated),
        }
    }
}
