/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialOverview {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "credential_data")]
    pub credential_data: Box<models::CredentialDataOverview>,
    #[serde(rename = "credential_type")]
    pub credential_type: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(
        rename = "user_label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_label: Option<Option<String>>,
}

impl CredentialOverview {
    pub fn new(
        created_at: String,
        credential_data: models::CredentialDataOverview,
        credential_type: String,
        id: uuid::Uuid,
        updated_at: String,
        user_id: uuid::Uuid,
    ) -> CredentialOverview {
        CredentialOverview {
            created_at,
            credential_data: Box::new(credential_data),
            credential_type,
            id,
            updated_at,
            user_id,
            user_label: None,
        }
    }
}
