/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CredentialDataOverview {
    CredentialDataOverviewOneOf(Box<models::CredentialDataOverviewOneOf>),
    String(String),
    CredentialDataOverviewOneOf1(Box<models::CredentialDataOverviewOneOf1>),
}

impl Default for CredentialDataOverview {
    fn default() -> Self {
        Self::CredentialDataOverviewOneOf(Default::default())
    }
}
