/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialDataOverviewOneOfHash {
    #[serde(rename = "algorithm")]
    pub algorithm: String,
    #[serde(rename = "hash_iterations")]
    pub hash_iterations: i32,
}

impl CredentialDataOverviewOneOfHash {
    pub fn new(algorithm: String, hash_iterations: i32) -> CredentialDataOverviewOneOfHash {
        CredentialDataOverviewOneOfHash {
            algorithm,
            hash_iterations,
        }
    }
}
