/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteUserCredentialResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "realm_name")]
    pub realm_name: String,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl DeleteUserCredentialResponse {
    pub fn new(
        message: String,
        realm_name: String,
        user_id: uuid::Uuid,
    ) -> DeleteUserCredentialResponse {
        DeleteUserCredentialResponse {
            message,
            realm_name,
            user_id,
        }
    }
}
