/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteRoleResponse {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "realm_name")]
    pub realm_name: String,
    #[serde(rename = "role_id")]
    pub role_id: uuid::Uuid,
}

impl DeleteRoleResponse {
    pub fn new(message: String, realm_name: String, role_id: uuid::Uuid) -> DeleteRoleResponse {
        DeleteRoleResponse {
            message,
            realm_name,
            role_id,
        }
    }
}
