/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateRecoveryCodesRequest {
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "code_format")]
    pub code_format: String,
}

impl GenerateRecoveryCodesRequest {
    pub fn new(amount: i32, code_format: String) -> GenerateRecoveryCodesRequest {
        GenerateRecoveryCodesRequest {
            amount,
            code_format,
        }
    }
}
