/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateRecoveryCodesResponse {
    #[serde(rename = "codes")]
    pub codes: Vec<String>,
}

impl GenerateRecoveryCodesResponse {
    pub fn new(codes: Vec<String>) -> GenerateRecoveryCodesResponse {
        GenerateRecoveryCodesResponse { codes }
    }
}
