/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetClientResponse {
    #[serde(rename = "data")]
    pub data: Box<models::Client>,
}

impl GetClientResponse {
    pub fn new(data: models::Client) -> GetClientResponse {
        GetClientResponse {
            data: Box::new(data),
        }
    }
}
