/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOpenIdConfigurationResponse {
    #[serde(rename = "authorization_endpoint")]
    pub authorization_endpoint: String,
    #[serde(rename = "end_session_endpoint")]
    pub end_session_endpoint: String,
    #[serde(rename = "grant_types_supported")]
    pub grant_types_supported: Vec<String>,
    #[serde(rename = "introspection_endpoint")]
    pub introspection_endpoint: String,
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "jwks_uri")]
    pub jwks_uri: String,
    #[serde(rename = "revocation_endpoint")]
    pub revocation_endpoint: String,
    #[serde(rename = "token_endpoint")]
    pub token_endpoint: String,
    #[serde(rename = "userinfo_endpoint")]
    pub userinfo_endpoint: String,
}

impl GetOpenIdConfigurationResponse {
    pub fn new(
        authorization_endpoint: String,
        end_session_endpoint: String,
        grant_types_supported: Vec<String>,
        introspection_endpoint: String,
        issuer: String,
        jwks_uri: String,
        revocation_endpoint: String,
        token_endpoint: String,
        userinfo_endpoint: String,
    ) -> GetOpenIdConfigurationResponse {
        GetOpenIdConfigurationResponse {
            authorization_endpoint,
            end_session_endpoint,
            grant_types_supported,
            introspection_endpoint,
            issuer,
            jwks_uri,
            revocation_endpoint,
            token_endpoint,
            userinfo_endpoint,
        }
    }
}
