/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUserCredentialsResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::CredentialOverview>,
}

impl GetUserCredentialsResponse {
    pub fn new(data: Vec<models::CredentialOverview>) -> GetUserCredentialsResponse {
        GetUserCredentialsResponse { data }
    }
}
