/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebhooksResponse {
    #[serde(rename = "data")]
    pub data: Vec<models::Webhook>,
}

impl GetWebhooksResponse {
    pub fn new(data: Vec<models::Webhook>) -> GetWebhooksResponse {
        GetWebhooksResponse { data }
    }
}
