/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityProviderPresentation {
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "login_url")]
    pub login_url: String,
}

impl IdentityProviderPresentation {
    pub fn new(
        display_name: String,
        icon: String,
        id: String,
        kind: String,
        login_url: String,
    ) -> IdentityProviderPresentation {
        IdentityProviderPresentation {
            display_name,
            icon,
            id,
            kind,
            login_url,
        }
    }
}
