/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntrospectRequestValidator {
    #[serde(
        rename = "client_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<String>>,
    #[serde(
        rename = "client_secret",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_secret: Option<Option<String>>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    #[serde(
        rename = "token_type_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token_type_hint: Option<Option<String>>,
}

impl IntrospectRequestValidator {
    pub fn new() -> IntrospectRequestValidator {
        IntrospectRequestValidator {
            client_id: None,
            client_secret: None,
            token: None,
            token_type_hint: None,
        }
    }
}
