/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwkKey {
    #[serde(rename = "alg")]
    pub alg: String,
    #[serde(rename = "e")]
    pub e: String,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "kty")]
    pub kty: String,
    #[serde(rename = "n")]
    pub n: String,
    #[serde(rename = "use")]
    pub r#use: String,
    #[serde(rename = "x5c")]
    pub x5c: Vec<String>,
    #[serde(rename = "x5t")]
    pub x5t: String,
}

impl JwkKey {
    pub fn new(
        alg: String,
        e: String,
        kid: String,
        kty: String,
        n: String,
        r#use: String,
        x5c: Vec<String>,
        x5t: String,
    ) -> JwkKey {
        JwkKey {
            alg,
            e,
            kid,
            kty,
            n,
            r#use,
            x5c,
            x5t,
        }
    }
}
