/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtToken {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
    #[serde(
        rename = "id_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id_token: Option<Option<String>>,
    #[serde(rename = "refresh_token")]
    pub refresh_token: String,
    #[serde(rename = "token_type")]
    pub token_type: String,
}

impl JwtToken {
    pub fn new(
        access_token: String,
        expires_in: i32,
        refresh_token: String,
        token_type: String,
    ) -> JwtToken {
        JwtToken {
            access_token,
            expires_in,
            id_token: None,
            refresh_token,
            token_type,
        }
    }
}
