/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogoutRequestValidator {
    #[serde(
        rename = "client_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<String>>,
    #[serde(
        rename = "id_token_hint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id_token_hint: Option<Option<String>>,
    #[serde(
        rename = "post_logout_redirect_uri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub post_logout_redirect_uri: Option<Option<String>>,
    #[serde(
        rename = "state",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub state: Option<Option<String>>,
}

impl LogoutRequestValidator {
    pub fn new() -> LogoutRequestValidator {
        LogoutRequestValidator {
            client_id: None,
            id_token_hint: None,
            post_logout_redirect_uri: None,
            state: None,
        }
    }
}
