/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OtpVerifyRequest {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl OtpVerifyRequest {
    pub fn new(code: String, label: String, secret: String) -> OtpVerifyRequest {
        OtpVerifyRequest {
            code,
            label,
            secret,
        }
    }
}
