/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permissions {
    #[serde(rename = "create_client")]
    CreateClient,
    #[serde(rename = "manage_authorization")]
    ManageAuthorization,
    #[serde(rename = "manage_clients")]
    ManageClients,
    #[serde(rename = "manage_events")]
    ManageEvents,
    #[serde(rename = "manage_identity_providers")]
    ManageIdentityProviders,
    #[serde(rename = "manage_realm")]
    ManageRealm,
    #[serde(rename = "manage_users")]
    ManageUsers,
    #[serde(rename = "manage_roles")]
    ManageRoles,
    #[serde(rename = "query_clients")]
    QueryClients,
    #[serde(rename = "query_groups")]
    QueryGroups,
    #[serde(rename = "query_realms")]
    QueryRealms,
    #[serde(rename = "query_users")]
    QueryUsers,
    #[serde(rename = "view_authorization")]
    ViewAuthorization,
    #[serde(rename = "view_clients")]
    ViewClients,
    #[serde(rename = "view_events")]
    ViewEvents,
    #[serde(rename = "view_identity_providers")]
    ViewIdentityProviders,
    #[serde(rename = "view_realm")]
    ViewRealm,
    #[serde(rename = "view_users")]
    ViewUsers,
    #[serde(rename = "view_roles")]
    ViewRoles,
    #[serde(rename = "manage_webhooks")]
    ManageWebhooks,
    #[serde(rename = "query_webhooks")]
    QueryWebhooks,
    #[serde(rename = "view_webhooks")]
    ViewWebhooks,
    #[serde(rename = "manage_client_scopes")]
    ManageClientScopes,
    #[serde(rename = "query_client_scopes")]
    QueryClientScopes,
    #[serde(rename = "view_client_scopes")]
    ViewClientScopes,
}

impl std::fmt::Display for Permissions {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreateClient => write!(f, "create_client"),
            Self::ManageAuthorization => write!(f, "manage_authorization"),
            Self::ManageClients => write!(f, "manage_clients"),
            Self::ManageEvents => write!(f, "manage_events"),
            Self::ManageIdentityProviders => write!(f, "manage_identity_providers"),
            Self::ManageRealm => write!(f, "manage_realm"),
            Self::ManageUsers => write!(f, "manage_users"),
            Self::ManageRoles => write!(f, "manage_roles"),
            Self::QueryClients => write!(f, "query_clients"),
            Self::QueryGroups => write!(f, "query_groups"),
            Self::QueryRealms => write!(f, "query_realms"),
            Self::QueryUsers => write!(f, "query_users"),
            Self::ViewAuthorization => write!(f, "view_authorization"),
            Self::ViewClients => write!(f, "view_clients"),
            Self::ViewEvents => write!(f, "view_events"),
            Self::ViewIdentityProviders => write!(f, "view_identity_providers"),
            Self::ViewRealm => write!(f, "view_realm"),
            Self::ViewUsers => write!(f, "view_users"),
            Self::ViewRoles => write!(f, "view_roles"),
            Self::ManageWebhooks => write!(f, "manage_webhooks"),
            Self::QueryWebhooks => write!(f, "query_webhooks"),
            Self::ViewWebhooks => write!(f, "view_webhooks"),
            Self::ManageClientScopes => write!(f, "manage_client_scopes"),
            Self::QueryClientScopes => write!(f, "query_client_scopes"),
            Self::ViewClientScopes => write!(f, "view_client_scopes"),
        }
    }
}

impl Default for Permissions {
    fn default() -> Permissions {
        Self::CreateClient
    }
}
