/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtocolMapper {
    #[serde(rename = "client_scope_id")]
    pub client_scope_id: uuid::Uuid,
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "mapper_type")]
    pub mapper_type: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl ProtocolMapper {
    pub fn new(
        client_scope_id: uuid::Uuid,
        config: Option<serde_json::Value>,
        created_at: String,
        id: uuid::Uuid,
        mapper_type: String,
        name: String,
    ) -> ProtocolMapper {
        ProtocolMapper {
            client_scope_id,
            config,
            created_at,
            id,
            mapper_type,
            name,
        }
    }
}
