/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProviderResponse {
    #[serde(rename = "config", deserialize_with = "Option::deserialize")]
    pub config: Option<serde_json::Value>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(
        rename = "last_sync_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_sync_at: Option<Option<String>>,
    #[serde(
        rename = "last_sync_status",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_sync_status: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "priority")]
    pub priority: i32,
    #[serde(rename = "provider_type")]
    pub provider_type: String,
    #[serde(rename = "realm_id")]
    pub realm_id: String,
    #[serde(rename = "sync_enabled")]
    pub sync_enabled: bool,
    #[serde(
        rename = "sync_interval_minutes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sync_interval_minutes: Option<Option<i32>>,
    #[serde(rename = "sync_mode")]
    pub sync_mode: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ProviderResponse {
    pub fn new(
        config: Option<serde_json::Value>,
        created_at: String,
        enabled: bool,
        id: String,
        name: String,
        priority: i32,
        provider_type: String,
        realm_id: String,
        sync_enabled: bool,
        sync_mode: String,
        updated_at: String,
    ) -> ProviderResponse {
        ProviderResponse {
            config,
            created_at,
            enabled,
            id,
            last_sync_at: None,
            last_sync_status: None,
            name,
            priority,
            provider_type,
            realm_id,
            sync_enabled,
            sync_interval_minutes: None,
            sync_mode,
            updated_at,
        }
    }
}
