/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Realm {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "settings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub settings: Option<Option<Box<models::RealmSetting>>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Realm {
    pub fn new(created_at: String, id: uuid::Uuid, name: String, updated_at: String) -> Realm {
        Realm {
            created_at,
            id,
            name,
            settings: None,
            updated_at,
        }
    }
}
