/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmSetting {
    #[serde(
        rename = "default_signing_algorithm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_signing_algorithm: Option<Option<String>>,
    #[serde(rename = "forgot_password_enabled")]
    pub forgot_password_enabled: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "magic_link_enabled")]
    pub magic_link_enabled: bool,
    #[serde(rename = "magic_link_ttl")]
    pub magic_link_ttl: i32,
    #[serde(rename = "realm_id")]
    pub realm_id: uuid::Uuid,
    #[serde(rename = "remember_me_enabled")]
    pub remember_me_enabled: bool,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "user_registration_enabled")]
    pub user_registration_enabled: bool,
}

impl RealmSetting {
    pub fn new(
        forgot_password_enabled: bool,
        id: uuid::Uuid,
        magic_link_enabled: bool,
        magic_link_ttl: i32,
        realm_id: uuid::Uuid,
        remember_me_enabled: bool,
        updated_at: String,
        user_registration_enabled: bool,
    ) -> RealmSetting {
        RealmSetting {
            default_signing_algorithm: None,
            forgot_password_enabled,
            id,
            magic_link_enabled,
            magic_link_ttl,
            realm_id,
            remember_me_enabled,
            updated_at,
            user_registration_enabled,
        }
    }
}
