/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealmLoginSetting {
    #[serde(rename = "forgot_password_enabled")]
    pub forgot_password_enabled: bool,
    #[serde(rename = "identity_providers")]
    pub identity_providers: Vec<models::IdentityProviderPresentation>,
    #[serde(rename = "magic_link_enabled")]
    pub magic_link_enabled: bool,
    #[serde(rename = "magic_link_ttl")]
    pub magic_link_ttl: i32,
    #[serde(rename = "remember_me_enabled")]
    pub remember_me_enabled: bool,
    #[serde(rename = "user_registration_enabled")]
    pub user_registration_enabled: bool,
}

impl RealmLoginSetting {
    pub fn new(
        forgot_password_enabled: bool,
        identity_providers: Vec<models::IdentityProviderPresentation>,
        magic_link_enabled: bool,
        magic_link_ttl: i32,
        remember_me_enabled: bool,
        user_registration_enabled: bool,
    ) -> RealmLoginSetting {
        RealmLoginSetting {
            forgot_password_enabled,
            identity_providers,
            magic_link_enabled,
            magic_link_ttl,
            remember_me_enabled,
            user_registration_enabled,
        }
    }
}
