/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RedirectUri {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl RedirectUri {
    pub fn new(
        client_id: uuid::Uuid,
        created_at: String,
        enabled: bool,
        id: uuid::Uuid,
        updated_at: String,
        value: String,
    ) -> RedirectUri {
        RedirectUri {
            client_id,
            created_at,
            enabled,
            id,
            updated_at,
            value,
        }
    }
}
