/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequiredAction {
    #[serde(rename = "configure_otp")]
    ConfigureOtp,
    #[serde(rename = "verify_email")]
    VerifyEmail,
    #[serde(rename = "update_password")]
    UpdatePassword,
}

impl std::fmt::Display for RequiredAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ConfigureOtp => write!(f, "configure_otp"),
            Self::VerifyEmail => write!(f, "verify_email"),
            Self::UpdatePassword => write!(f, "update_password"),
        }
    }
}

impl Default for RequiredAction {
    fn default() -> RequiredAction {
        Self::ConfigureOtp
    }
}
