/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResetPasswordValidator {
    #[serde(rename = "credential_type", skip_serializing_if = "Option::is_none")]
    pub credential_type: Option<String>,
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ResetPasswordValidator {
    pub fn new() -> ResetPasswordValidator {
        ResetPasswordValidator {
            credential_type: None,
            temporary: None,
            value: None,
        }
    }
}
