/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SecurityEvent {
    #[serde(
        rename = "actor_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "actor_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_type: Option<Option<models::ActorType>>,
    #[serde(
        rename = "details",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub details: Option<Option<serde_json::Value>>,
    #[serde(rename = "event_type")]
    pub event_type: models::SecurityEventType,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "ip_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ip_address: Option<Option<String>>,
    #[serde(rename = "realm_id")]
    pub realm_id: uuid::Uuid,
    #[serde(
        rename = "resource",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: models::EventStatus,
    #[serde(
        rename = "target_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "target_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_type: Option<Option<String>>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(
        rename = "trace_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trace_id: Option<Option<String>>,
    #[serde(
        rename = "user_agent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_agent: Option<Option<String>>,
}

impl SecurityEvent {
    pub fn new(
        event_type: models::SecurityEventType,
        id: uuid::Uuid,
        realm_id: uuid::Uuid,
        status: models::EventStatus,
        timestamp: String,
    ) -> SecurityEvent {
        SecurityEvent {
            actor_id: None,
            actor_type: None,
            details: None,
            event_type,
            id,
            ip_address: None,
            realm_id,
            resource: None,
            status,
            target_id: None,
            target_type: None,
            timestamp,
            trace_id: None,
            user_agent: None,
        }
    }
}
