/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityEventType {
    #[serde(rename = "login_success")]
    LoginSuccess,
    #[serde(rename = "login_failure")]
    LoginFailure,
    #[serde(rename = "password_reset")]
    PasswordReset,
    #[serde(rename = "user_created")]
    UserCreated,
    #[serde(rename = "user_deleted")]
    UserDeleted,
    #[serde(rename = "role_assigned")]
    RoleAssigned,
    #[serde(rename = "role_unassigned")]
    RoleUnassigned,
    #[serde(rename = "role_created")]
    RoleCreated,
    #[serde(rename = "role_removed")]
    RoleRemoved,
    #[serde(rename = "client_created")]
    ClientCreated,
    #[serde(rename = "client_deleted")]
    ClientDeleted,
    #[serde(rename = "client_secret_rotated")]
    ClientSecretRotated,
    #[serde(rename = "realm_config_changed")]
    RealmConfigChanged,
}

impl std::fmt::Display for SecurityEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LoginSuccess => write!(f, "login_success"),
            Self::LoginFailure => write!(f, "login_failure"),
            Self::PasswordReset => write!(f, "password_reset"),
            Self::UserCreated => write!(f, "user_created"),
            Self::UserDeleted => write!(f, "user_deleted"),
            Self::RoleAssigned => write!(f, "role_assigned"),
            Self::RoleUnassigned => write!(f, "role_unassigned"),
            Self::RoleCreated => write!(f, "role_created"),
            Self::RoleRemoved => write!(f, "role_removed"),
            Self::ClientCreated => write!(f, "client_created"),
            Self::ClientDeleted => write!(f, "client_deleted"),
            Self::ClientSecretRotated => write!(f, "client_secret_rotated"),
            Self::RealmConfigChanged => write!(f, "realm_config_changed"),
        }
    }
}

impl Default for SecurityEventType {
    fn default() -> SecurityEventType {
        Self::LoginSuccess
    }
}
