/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetupOtpResponse {
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "otpauth_url")]
    pub otpauth_url: String,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl SetupOtpResponse {
    pub fn new(issuer: String, otpauth_url: String, secret: String) -> SetupOtpResponse {
        SetupOtpResponse {
            issuer,
            otpauth_url,
            secret,
        }
    }
}
