/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SyncUsersResponse {
    #[serde(
        rename = "completed_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub completed_at: Option<Option<String>>,
    #[serde(rename = "created")]
    pub created: i32,
    #[serde(rename = "disabled")]
    pub disabled: i32,
    #[serde(rename = "failed")]
    pub failed: i32,
    #[serde(
        rename = "started_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub started_at: Option<Option<String>>,
    #[serde(rename = "total_processed")]
    pub total_processed: i32,
    #[serde(rename = "updated")]
    pub updated: i32,
}

impl SyncUsersResponse {
    pub fn new(
        created: i32,
        disabled: i32,
        failed: i32,
        total_processed: i32,
        updated: i32,
    ) -> SyncUsersResponse {
        SyncUsersResponse {
            completed_at: None,
            created,
            disabled,
            failed,
            started_at: None,
            total_processed,
            updated,
        }
    }
}
