/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenIntrospectionResponse {
    #[serde(rename = "active")]
    pub active: bool,
    #[serde(
        rename = "aud",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub aud: Option<Option<String>>,
    #[serde(
        rename = "client_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<String>>,
    #[serde(
        rename = "exp",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub exp: Option<Option<i64>>,
    #[serde(
        rename = "iat",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub iat: Option<Option<i64>>,
    #[serde(
        rename = "iss",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub iss: Option<Option<String>>,
    #[serde(
        rename = "jti",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub jti: Option<Option<String>>,
    #[serde(
        rename = "nbf",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nbf: Option<Option<i64>>,
    #[serde(
        rename = "realm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub realm: Option<Option<String>>,
    #[serde(
        rename = "scope",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scope: Option<Option<String>>,
    #[serde(
        rename = "sub",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sub: Option<Option<String>>,
    #[serde(
        rename = "token_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub token_type: Option<Option<String>>,
    #[serde(
        rename = "username",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub username: Option<Option<String>>,
}

impl TokenIntrospectionResponse {
    pub fn new(active: bool) -> TokenIntrospectionResponse {
        TokenIntrospectionResponse {
            active,
            aud: None,
            client_id: None,
            exp: None,
            iat: None,
            iss: None,
            jti: None,
            nbf: None,
            realm: None,
            scope: None,
            sub: None,
            token_type: None,
            username: None,
        }
    }
}
