/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProviderResponse {
    #[serde(rename = "data")]
    pub data: Box<models::ProviderResponse>,
}

impl UpdateProviderResponse {
    pub fn new(data: models::ProviderResponse) -> UpdateProviderResponse {
        UpdateProviderResponse {
            data: Box::new(data),
        }
    }
}
