/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRealmSettingResponse {
    #[serde(rename = "data")]
    pub data: Box<models::Realm>,
}

impl UpdateRealmSettingResponse {
    pub fn new(data: models::Realm) -> UpdateRealmSettingResponse {
        UpdateRealmSettingResponse {
            data: Box::new(data),
        }
    }
}
