/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRolePermissionsValidator {
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl UpdateRolePermissionsValidator {
    pub fn new(permissions: Vec<String>) -> UpdateRolePermissionsValidator {
        UpdateRolePermissionsValidator { permissions }
    }
}
