/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRealmSettingValidator {
    #[serde(
        rename = "default_signing_algorithm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_signing_algorithm: Option<Option<String>>,
    #[serde(
        rename = "forgot_password_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub forgot_password_enabled: Option<Option<bool>>,
    #[serde(
        rename = "magic_link_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub magic_link_enabled: Option<Option<bool>>,
    #[serde(
        rename = "magic_link_ttl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub magic_link_ttl: Option<Option<i32>>,
    #[serde(
        rename = "remember_me_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub remember_me_enabled: Option<Option<bool>>,
    #[serde(
        rename = "user_registration_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_registration_enabled: Option<Option<bool>>,
}

impl UpdateRealmSettingValidator {
    pub fn new() -> UpdateRealmSettingValidator {
        UpdateRealmSettingValidator {
            default_signing_algorithm: None,
            forgot_password_enabled: None,
            magic_link_enabled: None,
            magic_link_ttl: None,
            remember_me_enabled: None,
            user_registration_enabled: None,
        }
    }
}
