/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(
        rename = "client_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "email_verified")]
    pub email_verified: bool,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "firstname")]
    pub firstname: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "lastname")]
    pub lastname: String,
    #[serde(
        rename = "realm",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub realm: Option<Option<Box<models::Realm>>>,
    #[serde(rename = "realm_id")]
    pub realm_id: uuid::Uuid,
    #[serde(rename = "required_actions")]
    pub required_actions: Vec<models::RequiredAction>,
    #[serde(
        rename = "roles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub roles: Option<Option<Vec<models::Role>>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl User {
    pub fn new(
        created_at: String,
        email: String,
        email_verified: bool,
        enabled: bool,
        firstname: String,
        id: uuid::Uuid,
        lastname: String,
        realm_id: uuid::Uuid,
        required_actions: Vec<models::RequiredAction>,
        updated_at: String,
        username: String,
    ) -> User {
        User {
            client_id: None,
            created_at,
            email,
            email_verified,
            enabled,
            firstname,
            id,
            lastname,
            realm: None,
            realm_id,
            required_actions,
            roles: None,
            updated_at,
            username,
        }
    }
}
