/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationError {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl ValidationError {
    pub fn new(field: String, message: String) -> ValidationError {
        ValidationError { field, message }
    }
}
