/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebhookTrigger {
    #[serde(rename = "user.created")]
    UserCreated,
    #[serde(rename = "user.updated")]
    UserUpdated,
    #[serde(rename = "user.deleted")]
    UserDeleted,
    #[serde(rename = "user.role.assigned")]
    UserRoleAssigned,
    #[serde(rename = "user.role.unassigned")]
    UserRoleUnassigned,
    #[serde(rename = "user.bulk_deleted")]
    UserBulkDeleted,
    #[serde(rename = "user.credentials.deleted")]
    UserCredentialsDeleted,
    #[serde(rename = "auth.reset_password")]
    AuthResetPassword,
    #[serde(rename = "client.created")]
    ClientCreated,
    #[serde(rename = "client.updated")]
    ClientUpdated,
    #[serde(rename = "client.deleted")]
    ClientDeleted,
    #[serde(rename = "client.role.created")]
    ClientRoleCreated,
    #[serde(rename = "client.role.updated")]
    ClientRoleUpdated,
    #[serde(rename = "redirect_uri.created")]
    RedirectUriCreated,
    #[serde(rename = "redirect_uri.updated")]
    RedirectUriUpdated,
    #[serde(rename = "redirect_uri.deleted")]
    RedirectUriDeleted,
    #[serde(rename = "role.created")]
    RoleCreated,
    #[serde(rename = "role.updated")]
    RoleUpdated,
    #[serde(rename = "role.deleted")]
    RoleDeleted,
    #[serde(rename = "role.permission.updated")]
    RolePermissionUpdated,
    #[serde(rename = "realm.created")]
    RealmCreated,
    #[serde(rename = "realm.updated")]
    RealmUpdated,
    #[serde(rename = "realm.deleted")]
    RealmDeleted,
    #[serde(rename = "realm.settings.updated")]
    RealmSettingsUpdated,
    #[serde(rename = "webhook.created")]
    WebhookCreated,
    #[serde(rename = "webhook.updated")]
    WebhookUpdated,
    #[serde(rename = "webhook.deleted")]
    WebhookDeleted,
}

impl std::fmt::Display for WebhookTrigger {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserCreated => write!(f, "user.created"),
            Self::UserUpdated => write!(f, "user.updated"),
            Self::UserDeleted => write!(f, "user.deleted"),
            Self::UserRoleAssigned => write!(f, "user.role.assigned"),
            Self::UserRoleUnassigned => write!(f, "user.role.unassigned"),
            Self::UserBulkDeleted => write!(f, "user.bulk_deleted"),
            Self::UserCredentialsDeleted => write!(f, "user.credentials.deleted"),
            Self::AuthResetPassword => write!(f, "auth.reset_password"),
            Self::ClientCreated => write!(f, "client.created"),
            Self::ClientUpdated => write!(f, "client.updated"),
            Self::ClientDeleted => write!(f, "client.deleted"),
            Self::ClientRoleCreated => write!(f, "client.role.created"),
            Self::ClientRoleUpdated => write!(f, "client.role.updated"),
            Self::RedirectUriCreated => write!(f, "redirect_uri.created"),
            Self::RedirectUriUpdated => write!(f, "redirect_uri.updated"),
            Self::RedirectUriDeleted => write!(f, "redirect_uri.deleted"),
            Self::RoleCreated => write!(f, "role.created"),
            Self::RoleUpdated => write!(f, "role.updated"),
            Self::RoleDeleted => write!(f, "role.deleted"),
            Self::RolePermissionUpdated => write!(f, "role.permission.updated"),
            Self::RealmCreated => write!(f, "realm.created"),
            Self::RealmUpdated => write!(f, "realm.updated"),
            Self::RealmDeleted => write!(f, "realm.deleted"),
            Self::RealmSettingsUpdated => write!(f, "realm.settings.updated"),
            Self::WebhookCreated => write!(f, "webhook.created"),
            Self::WebhookUpdated => write!(f, "webhook.updated"),
            Self::WebhookDeleted => write!(f, "webhook.deleted"),
        }
    }
}

impl Default for WebhookTrigger {
    fn default() -> WebhookTrigger {
        Self::UserCreated
    }
}
