/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Webhook {
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "headers")]
    pub headers: std::collections::HashMap<String, String>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(rename = "subscribers")]
    pub subscribers: Vec<models::WebhookSubscriber>,
    #[serde(
        rename = "triggered_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub triggered_at: Option<Option<String>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl Webhook {
    pub fn new(
        created_at: String,
        endpoint: String,
        headers: std::collections::HashMap<String, String>,
        id: uuid::Uuid,
        subscribers: Vec<models::WebhookSubscriber>,
        updated_at: String,
    ) -> Webhook {
        Webhook {
            created_at,
            description: None,
            endpoint,
            headers,
            id,
            name: None,
            subscribers,
            triggered_at: None,
            updated_at,
        }
    }
}
