/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSubscriber {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: models::WebhookTrigger,
    #[serde(rename = "webhook_id")]
    pub webhook_id: uuid::Uuid,
}

impl WebhookSubscriber {
    pub fn new(
        id: uuid::Uuid,
        name: models::WebhookTrigger,
        webhook_id: uuid::Uuid,
    ) -> WebhookSubscriber {
        WebhookSubscriber {
            id,
            name,
            webhook_id,
        }
    }
}
